In [36]:
import numpy as np 
import gold_codes as gc

In [41]:
import importlib
importlib.reload(gc)

<module 'gold_codes' from '/Users/heller/Documents/binary_sequences/gold_codes/gold_codes.py'>

In [47]:
bits_per_symbol = 64

m = gc.gold_codec(11, bits_per_symbol)
m.shape

(64, 2047)

In [125]:
msg = np.frombuffer(b"abcdefghijklmnop", dtype=np.uint8)
print(msg.shape, msg.dtype)
tx_bits = np.unpackbits(msg).reshape(-1, bits_per_symbol)
tx_bits.shape, tx_bits.dtype, tx_bits

(16,) uint8


((2, 64),
 dtype('uint8'),
 array([[0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
         1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
         0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0],
        [0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
         1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
         1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0]],
       dtype=uint8))

In [130]:
tx_bipolar = tx_bits.astype(np.float32) * 2 - 1
x = tx_bipolar @ m/bits_per_symbol
x.shape, m.shape, np.std(x)

((2, 2047), (64, 2047), 0.12500668)

In [137]:
y = x + np.random.normal(scale=0, size=x.shape)

rx_hat = y @ m.T
print(rx_hat)

rx_bits = rx_hat > 0

print(rx_bits)


rx_bits == tx_bits


[[-31.90625  32.09375  32.09375 -31.90625 -31.90625 -31.90625 -31.90625
   32.09375 -31.90625  32.09375  32.09375 -31.90625 -31.90625 -31.90625
   32.09375 -31.90625 -31.90625  32.09375  32.09375 -31.90625 -31.90625
  -31.90625  32.09375  32.09375 -31.90625  32.09375  32.09375 -31.90625
  -31.90625  32.09375 -31.90625 -31.90625 -31.90625  32.09375  32.09375
  -31.90625 -31.90625  32.09375 -31.90625  32.09375 -31.90625  32.09375
   32.09375 -31.90625 -31.90625  32.09375  32.09375 -31.90625 -31.90625
   32.09375  32.09375 -31.90625 -31.90625  32.09375  32.09375  32.09375
  -31.90625  32.09375  32.09375 -31.90625  32.09375 -31.90625 -31.90625
  -31.90625]
 [-32.125    31.875    31.875   -32.125    31.875   -32.125   -32.125
   31.875   -32.125    31.875    31.875   -32.125    31.875   -32.125
   31.875   -32.125   -32.125    31.875    31.875   -32.125    31.875
  -32.125    31.875    31.875   -32.125    31.875    31.875   -32.125
   31.875    31.875   -32.125   -32.125   -32.125    31.875

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  Tru

In [145]:
np.packbits(rx_bits)

array([ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112], dtype=uint8)